version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: delivery_postgres_db
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend-app:
    build:
      context: ./backend-delivery
      dockerfile: ../Dockerfile
    container_name: delivery_backend_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/delivery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DEVTOOLS_REMOTE_SECRET: "dev-secret" # Segredo para devtools
    volumes:
      - ./backend-delivery/target/classes:/app/target/classes
    depends_on:
      - postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d delivery_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend-app-dev:
    build:
      context: ./frontend-delivery
      dockerfile: Dockerfile.dev
    container_name: delivery_frontend_app_dev
    ports:
      - "5173:5173"  # Porta do Vite dev server
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api
    volumes:
      # Monta o código fonte para hot-reload
      - ./frontend-delivery:/app
      # Evita sobrescrever node_modules
      - /app/node_modules
    depends_on:
      - backend-app
    command: npm run dev

volumes:
  postgres_data:
