version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: delivery_postgres_db
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    # Removido: volumes para persistência de dados

  backend-app:
    build:
      context: ./backend-delivery
      dockerfile: ../Dockerfile
    container_name: delivery_backend_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/delivery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d delivery_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend-app:
    build:
      context: ./frontend-delivery
      dockerfile: Dockerfile
    container_name: delivery_frontend_app
    ports:
      - "80:80"
    environment:
      VUE_APP_API_BASE_URL: http://backend-app:8080/api # Aponta para o serviço do backend
    depends_on:
      - backend-app

# Removido: declaração de volumes globais