services:
  db:
    image: postgres:16.6-alpine
    container_name: delivery_db_dev
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - delivery-network-dev

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/docker/backend/Dockerfile
    container_name: delivery_backend_dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/delivery_db
    depends_on:
      - db
    networks:
      - delivery-network-dev

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/docker/frontend/Dockerfile.dev
    container_name: delivery_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - delivery-network-dev

networks:
  delivery-network-dev:
    driver: bridge

volumes:
  postgres_dev_data:
