-- V1__init.sql

CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 50;

CREATE TABLE role (
    papel VARCHAR(255) NOT NULL,
    PRIMARY KEY (papel)
);

CREATE TABLE usuario (
    codigo BIGINT NOT NULL,
    cpf VARCHAR(255),
    data_nascimento DATE NOT NULL,
    email VARCHAR(255),
    endereco VARCHAR(255),
    nome VARCHAR(255),
    senha VARCHAR(255),
    PRIMARY KEY (codigo),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE usuarios_roles (
    usuario_codigo BIGINT NOT NULL,
    role_codigo VARCHAR(255) NOT NULL,
    CONSTRAINT fk_usuarios_roles_usuario FOREIGN KEY (usuario_codigo) REFERENCES usuario(codigo),
    CONSTRAINT fk_usuarios_roles_role FOREIGN KEY (role_codigo) REFERENCES role(papel)
);

CREATE TABLE estabelecimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ativo BOOLEAN NOT NULL,
    cnpj VARCHAR(255),
    endereco VARCHAR(255),
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    usuario_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_estabelecimento_cnpj UNIQUE (cnpj),
    CONSTRAINT fk_estabelecimento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(codigo)
);

CREATE TABLE produto (
    id_produto BIGINT NOT NULL,
    caminho_imagem VARCHAR(255),
    descricao VARCHAR(255),
    nome_produto VARCHAR(255),
    preco FLOAT NOT NULL,
    estabelecimento_id BIGINT,
    PRIMARY KEY (id_produto),
    CONSTRAINT fk_produto_estabelecimento FOREIGN KEY (estabelecimento_id) REFERENCES estabelecimento(id)
);

CREATE TABLE pedido (
    codigo_pedido BIGINT NOT NULL,
    codigo_cliente BIGINT,
    data_pedido TIMESTAMP,
    endereco_pedido VARCHAR(255),
    status VARCHAR(255),
    taxa_entrega FLOAT NOT NULL,
    valor_total FLOAT NOT NULL,
    PRIMARY KEY (codigo_pedido)
);

CREATE TABLE pedido_produtos (
    pedido_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    CONSTRAINT fk_pedido_produtos_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(codigo_pedido),
    CONSTRAINT fk_pedido_produtos_produto FOREIGN KEY (produto_id) REFERENCES produto(id_produto)
);

CREATE TABLE entrega (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    criado_em TIMESTAMP,
    endereco_destino VARCHAR(255),
    endereco_origem VARCHAR(255),
    entregue_em TIMESTAMP,
    status VARCHAR(255),
    tempo_estimado INTEGER,
    valor_entrega NUMERIC(38,2),
    entregador_id BIGINT,
    pedido_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_entrega_entregador FOREIGN KEY (entregador_id) REFERENCES usuario(codigo),
    CONSTRAINT fk_entrega_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(codigo_pedido)
);

CREATE TABLE pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data_pagamento TIMESTAMP,
    metodo_pagamento VARCHAR(255),
    status VARCHAR(255),
    transaction_id VARCHAR(255),
    valor DOUBLE PRECISION NOT NULL,
    pedido_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_pagamento_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(codigo_pedido)
);
