-- V1__init.sql (English version with fixed Identity)

CREATE TABLE roles (
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cpf VARCHAR(255),
    birth_date DATE NOT NULL,
    email VARCHAR(255),
    address VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_user_email UNIQUE (email)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_name) REFERENCES roles(name)
);

CREATE TABLE establishments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    active BOOLEAN NOT NULL,
    cnpj VARCHAR(255),
    address VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    user_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_establishment_cnpj UNIQUE (cnpj),
    CONSTRAINT fk_establishment_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    image_url VARCHAR(255),
    description VARCHAR(255),
    name VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    establishment_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_establishment FOREIGN KEY (establishment_id) REFERENCES establishments(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT,
    order_date TIMESTAMP,
    delivery_address VARCHAR(255),
    status VARCHAR(255),
    delivery_fee FLOAT NOT NULL,
    total_value FLOAT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE order_products (
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_order_products_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_products_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP,
    destination_address VARCHAR(255),
    origin_address VARCHAR(255),
    delivered_at TIMESTAMP,
    status VARCHAR(255),
    estimated_time INTEGER,
    delivery_value NUMERIC(38,2),
    courier_id BIGINT,
    order_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_delivery_courier FOREIGN KEY (courier_id) REFERENCES users(id),
    CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payment_date TIMESTAMP,
    payment_method VARCHAR(255),
    status VARCHAR(255),
    transaction_id VARCHAR(255),
    amount DOUBLE PRECISION NOT NULL,
    order_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
