-- V5__create_order_items.sql

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Migrate existing order_products data to order_items
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
SELECT op.order_id, op.product_id, 1, p.price
FROM order_products op
JOIN products p ON p.id = op.product_id;

-- Remove old join table after migration
DROP TABLE order_products;
