# Configurações do Banco de Dados PostgreSQL para produção
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# Configurações do Servidor
server.port=${PORT:8080}

# Configurações JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

# Configurações CORS
frontend.url=${FRONTEND_URL}